http://127.0.0.1:8000/api/v1/titles/1/reviews/1/comments/1/
# Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjc2NTc4OTg5LCJqdGkiOiI5NjYwZGMzYmE0MWY0MmVmODZmYjE5MTQ1MWY2MGFjMyIsInVzZXJfaWQiOjJ9.Vryx-pSASbfmGhA_rUCvm2WXkCOTq7Nmv5TrIDkP98M

###

POST http://127.0.0.1:8000/api/v1/titles/
Content-Type: application/json
# Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjc2NTc4OTg5LCJqdGkiOiI5NjYwZGMzYmE0MWY0MmVmODZmYjE5MTQ1MWY2MGFjMyIsInVzZXJfaWQiOjJ9.Vryx-pSASbfmGhA_rUCvm2WXkCOTq7Nmv5TrIDkP98M
{
"name": "string",
"year": 0,
"description": "string",
"genre": [
"string"
],
"category": "string"
}

###

POST http://127.0.0.1:8000/api/v1/groups/
Content-Type: application/json
Authorization: Token 385500225350d2912d1116317884a6ef16cf2ebe

{
    "title": "Админчик",
    "slug": "slav1",
    "description": "Группа Админа"
}

###

POST http://127.0.0.1:8000/api/v1/posts/44/comments/
Content-Type: application/json
Authorization: Token 385500225350d2912d1116317884a6ef16cf2ebe

{
    "text": "OK"
}

###

DELETE http://127.0.0.1:8000/api/v1/posts/43/
Authorization: Token 385500225350d2912d1116317884a6ef16cf2ebe

###

POST http://127.0.0.1:8000/api-token-auth/
Content-Type: application/json

{
    "username": "admin",
    "password": "Slava132!"
}


###

POST http://127.0.0.1:8000/auth/users/
Content-Type: application/json

{
    "username": "admin1",
    "password": "Administrator12"
}

###

POST http://127.0.0.1:8000/auth/jwt/create/
Content-Type: application/json

{
    "username": "admin1",
    "password": "Administrator12"
}