# Generated by Django 3.2 on 2023-03-10 20:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('3dcae825-e218-4c37-a18e-7e62fdcef953'), verbose_name='Код'),
        ),
    ]
