# Generated by Django 3.2 on 2023-03-10 06:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('f726b9e6-78f4-4d06-96ac-b69628488f47'), verbose_name='Код'),
        ),
    ]
