# Generated by Django 3.2 on 2023-03-10 20:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('1df0ca79-69ca-4b3c-9787-d0df6651bd46'), verbose_name='Код'),
        ),
    ]
