# Generated by Django 3.2 on 2023-03-09 07:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230309_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('5157cee0-fdb9-4b40-84be-218ac69479aa'), verbose_name='Код'),
        ),
    ]
