# Generated by Django 3.2 on 2023-03-10 21:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('ff705018-0f6c-4408-96ae-fac9cf5bdc22'), verbose_name='Код'),
        ),
    ]
