# Generated by Django 3.2 on 2023-03-10 11:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230310_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('873cbebb-60cb-4293-845f-e1305f8ec9fa'), verbose_name='Код'),
        ),
    ]
