# Generated by Django 3.2 on 2023-03-10 21:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('93e20d85-ad06-4c18-9962-16c1ead4a67b'), verbose_name='Код'),
        ),
    ]
