# Generated by Django 3.2 on 2023-03-10 21:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('25ed4fcb-250c-40df-9049-ef6dad6fdb75'), verbose_name='Код'),
        ),
    ]
