# Generated by Django 3.2 on 2023-03-10 11:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230310_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('1ad96e9a-cce0-4fa5-8a33-51fb2685a019'), verbose_name='Код'),
        ),
    ]
