# Generated by Django 3.2 on 2023-03-10 22:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('19f317e9-6cf3-4835-b839-55852c8e0749'), verbose_name='Код'),
        ),
    ]
