# Generated by Django 3.2 on 2023-03-10 22:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('3547b232-466f-431b-938e-501ed2b02aa4'), verbose_name='Код'),
        ),
    ]
