# Generated by Django 3.2 on 2023-03-10 12:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('6db1bdfe-ea76-459d-98f3-d26d0e8551a3'), verbose_name='Код'),
        ),
    ]
