# Generated by Django 3.2 on 2023-03-10 22:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('c2484294-5b2b-48fc-8247-191069c36d36'), verbose_name='Код'),
        ),
    ]
