# Generated by Django 3.2 on 2023-03-10 12:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('c4000524-b30d-451d-8c15-d2b16752aca9'), verbose_name='Код'),
        ),
    ]
