# Generated by Django 3.2 on 2023-03-12 08:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('ddd862f8-1dae-4abd-94f4-d9a097d0a9f7'), verbose_name='Код'),
        ),
    ]
