# Generated by Django 3.2 on 2023-03-12 08:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('277bfafb-4a58-465a-af7a-16319feefc5a'), verbose_name='Код'),
        ),
    ]
