# Generated by Django 3.2 on 2023-03-12 08:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('784711d2-73a6-4e7e-9520-56d17f0920f0'), verbose_name='Код'),
        ),
    ]
