# Generated by Django 3.2 on 2023-03-13 11:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('9e6d866b-9b70-4777-bd1a-62abc3ae15f7'), verbose_name='Код'),
        ),
    ]
