# Generated by Django 3.2 on 2023-03-14 04:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('bf88ffbb-8852-48a8-b0ff-7d64c0bb0f63'), verbose_name='Код'),
        ),
    ]
