# Generated by Django 3.2 on 2023-03-10 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230311_0027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['-id'], 'verbose_name': ('Произведение',), 'verbose_name_plural': ('Произведения',)},
        ),
    ]
