# Generated by Django 3.2 on 2023-03-10 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20230311_0044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['-year', 'name'], 'verbose_name': ('Произведение',), 'verbose_name_plural': ('Произведения',)},
        ),
    ]
