# Generated by Django 3.2 on 2023-03-12 08:18

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_title_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(db_index=True, help_text='Введите возможный год издания произведения', validators=[reviews.validators.my_year_validator], verbose_name='Год издания'),
        ),
    ]
