# Generated by Django 3.2 on 2023-03-13 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_alter_review_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenreTitle',
        ),
    ]
